---
title: "Class 16 MiniProject"
author: "Julia Napoli"
date: "11/19/2021"
output:
  pdf_document: default
  html_document: default
---

# Differential Expression Analysis

```{r}
library(DESeq2)
```


```{r}
metaFile <- "GSE37704_metadata.csv"
countFile <- "GSE37704_featurecounts.csv"
```

```{r}
# Import metadata and take a peak
colData = read.csv(metaFile, row.names=1)
head(colData)
```

```{r}
# Import countdata
countData = read.csv(countFile, row.names=1)
head(countData)
```

```{r}
# Note we need to remove the odd first $length col
countData <- as.matrix(countData[,2:7])

head(countData)
```

```{r}
# Filter count data where you have 0 read count across all samples.
#zeroData = which(rowSums(countData)==0, arr.ind = TRUE)
#head(zeroData)

counts <- countData[rowSums(countData) !=0,]
#counts <- countData[-zeroData[,1],]
head(counts)
```

```{r}
nrow(counts)
```

# PCA Analysis

Use base R `prcomp()` function for PCA of our counts data (from which I have removed the zeros).

```{r}
pca <- prcomp(t(counts))
summary(pca)
```

Quick plot
```{r}
plot(pca$x[,1:2])
```

```{r}
plot(pca$x[,1:2], pch = 16, col=as.factor(colData$condition))
text(pca$x[,1:2],labels = colData$condition)
```

This looks fine - the first PC separates out the KD from the cn.

# 3. DESeq Analysis

```{r}
library(DESeq2)
dds <- DESeqDataSetFromMatrix(counts,
                              colData,
                              design = ~condition
)
```

And run the DESeq analysis

```{r}
dds <- DESeq(dds)
res <- results(dds)
head(res)
```

```{r}
summary(res)
```

# Volcano plot

```{r}
plot(res$log2FoldChange, -log(res$padj))
```

```{r}
# Make a color vector for all genes
mycols <- rep("gray", nrow(res) )

# Color red the genes with absolute fold change above 2
mycols[ abs(res$log2FoldChange) > 2 ] <- "red"

# Color blue those with adjusted p-value less than 0.01
#  and absolute fold change more than 2
inds <- (res$padj < 0.01) & (abs(res$log2FoldChange) > 2 )
mycols[ inds ] <- "blue"

plot( res$log2FoldChange, -log(res$padj), col=mycols, xlab="Log2(FoldChange)", ylab="-Log(P-value)" )
```

Now let's add some annotations.

```{r}
library("AnnotationDbi")
library("org.Hs.eg.db")

columns(org.Hs.eg.db)
```

```{r}
res$symbol = mapIds(org.Hs.eg.db,
                    keys=row.names(res), 
                    keytype="ENSEMBL",
                    column="SYMBOL",
                    multiVals="first")

res$entrez = mapIds(org.Hs.eg.db,
                    keys=row.names(res),
                    keytype="ENSEMBL",
                    column="ENTREZID",
                    multiVals="first")

res$name =   mapIds(org.Hs.eg.db,
                    keys=row.names(res),
                    keytype="ENSEMBL",
                    column="GENENAME",
                    multiVals="first")

head(res, 10)
```

```{r}
res = res[order(res$pvalue),]
write.csv(res, file ="deseq_results.csv")
```

KEGG Pathways

```{r}
BiocManager::install(c("pathview", "gage", "gageData"))
```

```{r}
library(pathview)
```

```{r}
library(gage)
library(gageData)

data(kegg.sets.hs)
data(sigmet.idx.hs)

# Focus on signaling and metabolic pathways only
kegg.sets.hs = kegg.sets.hs[sigmet.idx.hs]

# Examine the first 3 pathways
head(kegg.sets.hs, 3)
```

```{r}
foldchanges = res$log2FoldChange
names(foldchanges) = res$entrez
head(foldchanges)
```

```{r}
# Get the results
keggres = gage(foldchanges, gsets=kegg.sets.hs)
```

```{r}
attributes(keggres)
```

```{r}
# Look at the first few down (less) pathways
head(keggres$less)
```

```{r}
pathview(gene.data=foldchanges, pathway.id="hsa04110")
```

![]hsa04110.png

```{r}
# A different PDF based output of the same data
pathview(gene.data=foldchanges, pathway.id="hsa04110", kegg.native=FALSE)
```

![]hsa04110.pathview.png

# Gene Ontology

```{r}
data(go.sets.hs)
data(go.subs.hs)

# Focus on Biological Process subset of GO
gobpsets = go.sets.hs[go.subs.hs$BP]

gobpres = gage(foldchanges, gsets=gobpsets, same.dir=TRUE)

lapply(gobpres, head)
```



